# on:
#   schedule:
#     - cron: "*/5 * * * *"
on: [push]

jobs:
  readme:
    runs-on: 	macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Edit README
      run: |
        echo "Today is $(date '+%A, %Y %b %d')" > README
        echo >> README
        echo >> README
        cal -hy $(date +%Y) >> README
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Harry Cao
        author_email: ngocthaicao@gmail.com
        message: "Auto update README"
        add: "README"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
