# on:
#   schedule:
#     - cron: "*/5 * * * *"
on: [push]

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Edit README
      run: |
        date > README.md
        echo >> README.md
        cal >> README.md
    - uses: EndBug/add-and-commit@v9
      with:
        author_name: Harry Cao
        author_email: ngocthaicao@gmail.com
        message: "Auto update README"
        add: "README.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
